#!/usr/bin/env bash
# Install and configure HAProxy for load balancing

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 100.26.225.174:80 check
    server web-02 18.209.224.170:80 check
EOT

# Check the HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Start and enable HAProxy service
sudo systemctl start haproxy
sudo systemctl enable haproxy
