#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive

mysql_password="$1"

backup_date=$(date +'%d-%m-%Y')

mysqldump -u root -p"$mysql_password" --all-databases > backup.sql

tar -czvf "$backup_date.tar.gz" backup.sql