#!/usr/bin/env bash
# This script displays listening ports and their associated PID/Program name.
if [[ $(id -u) -ne 0 ]]; then
  echo "This script needs to be run with sudo privileges."
  exit 1
fi
show_listening_ports() {
  netstat -tulnep
}

show_listening_ports
