#!/usr/bin/env bash
# This script pings an IP address passed as an argument.
# Check if an IP address is provided as an argument
if [[ $# -eq 0 ]]; then
  echo "Usage: $(basename "$0") {IP_ADDRESS}"
  exit 1
fi

ping_ip() {
  ip_address="$1"
  ping -c 5 "$ip_address"
}
ping_ip "$1"
