#!/usr/bin/env bash
# This bash script configures Nginx to run and listen on port 80

# Remove the default Nginx configuration (if needed)
sudo rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default Nginx configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply changes
sudo service nginx restart
