#!/usr/bin/env bash
# This script displays "Best School" 10 times and says "Hi" on the 9th iteration

count=1
while (( count <= 10 ))
do
    if (( count == 9 ))
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    (( count++ ))
done
