#!/usr/bin/env bash
# This script displays "Best School" for most iterations, "bad luck" for the 4th iteration, and "good luck" for the 8th iteration

count=1
while (( count <= 10 ))
do
    if (( count == 4 ))
    then
        echo "bad luck"
    elif (( count == 8 ))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( count++ ))
done
