#!/usr/bin/env bash
# This script listens on port 98 on localhost and prints the received data.
if [[ $(id -u) -ne 0 ]]; then
  echo "This script needs to be run with sudo privileges."
  exit 1
fi

listen_on_port_98() {
  nc -l -p 98
}
listen_on_port_98
