#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -i -E 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i -E 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
su nginx -s /bin/sh -c 'service nginx restart'
