#!/usr/bin/env bash
# This script connects to the server using SSH with a specific private key and user.

# Use the 'ssh' command with the private key and user
ssh -i ~/.ssh/school ubuntu@54.146.89.243
